version: "3"
services:
  postgres_dev_aid:
    container_name: 'postgres_dev_aid'
    restart: 'always'
    image: dev_aid/postgres
    build: ./postgres
    ports:
      - "5433:5432"
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "5"